frontend with typechecking (#101)
linter is broken currently

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -2,35 +2,65 @@ name: Pull Request
 
 on:
   push:
-    branches: [ main ]
+    branches: 
+    - main 
   pull_request:
-    branches: [ main ]
+    branches: 
+    - main
 
 jobs:
-  build:
+
+  # server: 
+  # can we run the server, is the API alright?
+  #
+  # Priority is to fail fast, so first can we compile and build 
+  # the server binary, then tests, and linting.
+  server:
+    defaults:
+      run:
+        working-directory: server
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v3
     - uses: cashapp/activate-hermit@v1
+    - name: build-server
+      run: go build ./cmd/server
     - name: test
-      run: cd server && go test ./...
+      run: go test ./...
+    - name: lint
+      run: golangci-lint run
 
-  lint:
+  # frontend: describes the steps we take to 
+  # ensure that the nuxt application is buildable.
+  # 
+  # The priority here is to fail fast on critical things.
+  # 1. We can actually build the application
+  # 2. It typechecks & lints
+  frontend:
     runs-on: ubuntu-latest
+    defaults:
+      run: 
+        working-directory: frontend
     steps:
     - uses: actions/checkout@v3
     - uses: cashapp/activate-hermit@v1
-    - name: shellcheck
-      run:  shellcheck bin/prmectl
-    - name: lint-golang
-      run: cd server && golangci-lint run
-    - name: lint-vue
-      run: cd frontend && yarn && yarn lint
-
-  generate:
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@v3
-    - uses: cashapp/activate-hermit@v1
+    - name: yarn
+      run: yarn
     - name: generate
-      run: cd frontend && yarn && yarn generate
+      run: yarn generate
+    - name: typecheck
+      run: yarn nuxi typecheck
+    - name: lint
+      run: | 
+        echo yarn eslint .
+        echo Linting for some reason is currently broken, and times out
+        exit 1
+  
+  # prmectl: just make sure that it's going to be ok.
+  prmectl:
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v3
+    - uses: cashapp/activate-hermit@v1
+    - name: shellcheck bin/prmectl
+      run:  shellcheck bin/prmectl
